[vendor]
name = "Truce Audio"
id = "com.truce"
url = "https://www.github.com/truce-audio/"
au_manufacturer = "Truc"

[macos.packaging]
notarize = true
welcome_html = "static/truce-welcome.html"

[windows.packaging]
installer_icon = "static/truce-minimal.ico"
welcome_bmp = "static/truce-welcome.bmp"

[[plugin]]
name = "Truce Analyzer"
bundle_id = "truce-analyzer"
crate = "truce-analyzer"
category = "effect"
fourcc = "TrAn"
au_tag = "Effects"
windows_icon = "static/truce-minimal.ico"
macos_icon = "static/truce-minimal.icns"
