[vendor]
name = "Truce Audio"
id = "com.truce"
url = "https://www.github.com/truce-audio/"
au_manufacturer = "Truc"

[macos.packaging]
notarize = true

[[plugin]]
name = "Truce Analyzer"
suffix = "truce-analyzer"
crate = "truce-analyzer"
category = "effect"
fourcc = "TrAn"
au_tag = "Effects"
